### ISSUE TITLE
allow numbers in the package name

### ISSUE THREAD

**Issue by codefromthecrypt** [inkeliz/karmem#101]
I am toying with the idea of making karm8s

See https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/6#issuecomment-1557022947

**Comment by codefromthecrypt** [comment]
I'm actually not personally going to pursue this, but I posted what I coverted from proto in case someone is interested. Unless I made a mistake, a huge model is fairly slow to use even if there aren't many fields serialized. https://gist.github.com/codefromthecrypt/e6b13bd2de275dc20be5b8847328efd3

**Comment by inkeliz** [comment]
At this moment, I am at the end of the semester in college, and I can't dedicate myself to this, right now.

However, I planning to propose "Karmem2" as my "Final Project" (in the next college-year). I intend to add someway to describe functions (such as gRPC), but focused to WASM, with ways to share memories and better describe whether there are copies or not. Also, supporting some "delta-copy", and as you notice some optional-fields.

I will investigate your use-case during the holidays, next month (I hope). 🙃

**Comment by codefromthecrypt** [comment]
good luck with your final months of school! see ya!
