### ISSUE TITLE
Correction on Golang+Protobuf comment

### ISSUE THREAD

**Issue by phillip-elm** [inkeliz/karmem#92]
This library looks pretty cool! That said, there's an incorrect statement in the README:

> That is something that Google Protobuf doesn't have, and malformed content will cause panic.

This is untrue. `proto.Unmarshal` returns an error when the data received isn't valid. gRPC would never be taken seriously if it fell over when a bad message is received...

**Comment by inkeliz** [comment]
I think I confuse `Google Protobuf` and `Google Flatbuffers`, since the names are similar and all benchmarks are comparing against `Flatbuffers`. In that case, Flatbuffers doesnt have any validation: https://github.com/google/flatbuffers/issues/5367.

I'll fix that message soon.
